### ISSUE TITLE
When is required to use pop and push_matrix() in lyte.frame? (Question)

### ISSUE THREAD

**Issue by SugarRayLua** [morew4rd/morew4rd.com#3]
Hi. I'm a novice lua programmer who is used to using Love2D and am enjoying trying out your alpha version of Lyte2D. However, it is not clear to me from your Lyte2D examples in what instances the programmer needs to use pop and push_matrix for when drawing in the lyte.frame loop of your API. I'd appreciate any further clarification on pop/push_matrix use you could provide.

Thanks!

**Comment by morew4rd** [comment]
Love2D has a similar API pair (push/pop) as well. Basically you save the current transformation state (technically it's a matrix) when you do a push. And pop restores it.

You can do translate (move the render location), scale (stretch in x or y) or rotate in between these two.

See this example: https://github.com/morew4rd/lyte2d/blob/main/examples/s05_canvas.lua#L42-L55
rotate is applied to the image, but not the text (because pop restored the transformation state to whatever it was before push.)

Another example would be (in simplified code)
``` 
   -- we will draw a head circle, and two eyes.
  head_loc_x = 100
  head_loc_y = 120
   push()
   translate(head_loc_x, head_loc_y) -- draw head in this location
   circle(0, 0, 100) -- center, radius: 100
   translate(-20, -20) -- move a bit left and up
   circle(0, 0, 20) -- left eye
   translate(40, 0) -- move to the right
   circle(0, 0, 20)
   pop()  -- now location is at wherever it was before.
```

(Well, I didn't change the colors, but I hope it makes sense.  Love2D should have better docs currently.)

**Comment by morew4rd** [comment]
BTW: 0.4 is coming soon, and it'll have a few API name changes, to make it more consistent and less error prone.

(People mixed up "frame" with sprite frames, and "clear" was not clear to folks, so these became "tick" and "cls" respectively, for example.)

**Comment by SugarRayLua** [comment]
Great, thanks-- that helped a lot! I've thought the purpose of "translate" in most engines was to move player/scene objects or even the scene.camera for a scene that was already created and rendered but never realized one could use translate to basically move the renderer and then give commands to draw at that new render location. Doing so reminds me of an old school "Etch- A Sketch" where you turned two knobs (translated) the drawing mechanism to a place on the screen surface to continue sketching (and from what you said if I "pushed" before doing so and then "popped" afterwards, my Etch A Sketch would return to its "home" position where it was before I moved the knows. I'll play around with that code snippet to gain a better understanding. 

:-)

**Comment by morew4rd** [comment]
Glad to hear that! Actually camera systems are just implemented with these primitives. (I'll have an example at some point.)

For now, closing this issue. If you need guidance on anything else please let me know.
